### ISSUE TITLE
"**** が実行できません" or "Illegal Command: ****" というエラーが出て実行できません

### ISSUE THREAD

**Issue by seikedon** [nanshiki/DOSVAXJ3#4]
Raspberry Pi 400 , 3A+にインストールして使おうとしていますが、マウントしたフォルダの中に入れているDOSVなどのDOSアプリケーションが動作しません。どのような原因が考えられるかわかるでしょうかn？何か気づくことがありましたらどなたか教えてくれないかなと思いました。
以下に状況を書きます。

1)SDL-IM-plus を先にビルド・インストール

2)DOSVAXJ3をビルド＆インストール

	git clone https://github.com/nanshiki/DOSVAXJ3.git
	./autogen.sh
	./configure
	make
	sudo make install

	[autoexec] #下を追加
	MOUNT C: ./hdd1
	C:

3)./hdd1にDOSプログラムをコピーして実行

"**** が実行できません" or "Illegal Command: ****" というエラーが出て実行できません。
フォルダ名"hdd1"をC:としてマウントして、その中に実行プログラムを入れています。
具体的には
	filmtn
	vz
	freedosのコマンド群

z:ドライブに入っている組み込みの外部コマンドは正常に動作します。
memなどですね。

**Comment by nanshiki** [comment]
@seikedon すみません。Linux で LFN 有効の場合にファイル名の大文字小文字を識別してしまっていたようです。
とりあえずは大文字で FILMTN や VZ と入力すれば実行できると思います。
修正しますので少々お待ちください。

**Comment by nanshiki** [comment]
@seikedon とりあえず Linux で問題がでないように修正しました。
Windows版には今回の不具合は発生しないのですが、他にも何点か修正する予定で、その後でバージョンを上げます。

**Comment by seikedon** [comment]
大変助かります。感謝いたします。
