### ISSUE TITLE
DOSVAXJ3が固まります…

### ISSUE THREAD

**Issue by chuntaro** [nanshiki/DOSVAXJ3#5]
https://github.com/microsoft/MS-DOS/blob/master/v2.0/bin/DEBUG.COM
↑この DEBUG.COM を落として DOSVAXJ3 で動かすと基本的には動きますが、A 0100 で正しいコードを入力後に G=0100 をすると DOSVAXJ3 が固まります…
固まらない様にする回避方法など有るでしょうか？

環境は Windows10 で dosboxj.conf 等は全てデフォルトの状態です。

**Comment by chuntaro** [comment]
![image](https://user-images.githubusercontent.com/7358590/176135362-45d3ad59-6941-439a-897e-62034ee62e93.png)
この後固まったり、何も起きずに落ちたり、reboot 何とかと表示されたりする直前の状態です。

**Comment by nanshiki** [comment]
回答が遅れてすみません。
g=100で実行するとDOSの終了ファンクションが呼び出されるまで止まりません。
この例の場合、mov [0150],alを実行後、次の105以降の命令が不定ですので暴走します。
DOSVAXJ3だけでなく実機でも暴走します。
gコマンドでブレークポイントを指定できますのでg=100 105等として105で止まるようにしてください。

**Comment by chuntaro** [comment]
すみません…自分がちゃんとgコマンドを理解してませんでした…
おっしゃる通り実行を終了するアドレスも必要でした。
説明ありがとうございました。
